AWSTemplateFormatVersion: 2010-09-09
Resources:

  CracklingRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: Crackling
      EndpointConfiguration:
        Types:
          - EDGE
      Description: API endpoint for Crackling
    Metadata:
      'AWS::CloudFormation::Designer':
        id: cec9eb71-520d-4c8e-b49d-6707666e37c7
  CracklingRestApiStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId: !Ref CracklingRestApiDeployment
      Description: Crackling Production API Stage
      MethodSettings:
        - DataTraceEnabled: 'true'
          HttpMethod: GET
          MetricsEnabled: 'true'
          ResourcePath: /
        - DataTraceEnabled: 'true'
          HttpMethod: POST
          MetricsEnabled: 'true'
          ResourcePath: /api-gateway-stack
          ThrottlingBurstLimit: '999'
        - DataTraceEnabled: 'true'
          HttpMethod: GET
          MetricsEnabled: 'true'
          ResourcePath: /api-gateway-stack
          ThrottlingBurstLimit: '555'
      RestApiId: !Ref CracklingRestApi
      StageName: CracklingProductionApi
      Variables:
        Stack: api-gateway-stack
    Metadata:
      'AWS::CloudFormation::Designer':
        id: fa21bebf-4f0a-46de-b488-ed609ec4515c
  CracklingRestApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref CracklingRestApi
    DependsOn:
      - PostSubmitJob
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8a5ba4db-dc88-4861-87f4-c2ef066286aa
      id: c70adb5e-ef22-41b5-b176-c4a49c272eb1
  SubmitJobResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref CracklingRestApi
      ParentId: !GetAtt 
        - CracklingRestApi
        - RootResourceId
      PathPart: submit
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1237aee6-1763-4764-8e61-cff47a07a281
  PostSubmitJob:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseTemplates:
              application/json: ''
            StatusCode: 200
        Type: AWS_PROXY
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateJobFunction.Arn}/invocations
      MethodResponses:
        - ResponseModels:
            application/json: Empty
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
          StatusCode: 200
      ResourceId: !Ref SubmitJobResource
      RestApiId: !Ref CracklingRestApi
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 20c69c84-7828-4853-8398-b77a31dbe46b
  ApiProxyPolicy:
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'dynamodb:GetItem'
              - 'dynamodb:GetRecords'
              - 'dynamodb:Query'
            Effect: Allow
            Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*'
        Version: 2012-10-17
      PolicyName: !Sub 'policygen-api_proxy_${AWS::Region}'
      Roles:
        - !Ref ApiProxyRole
    Type: 'AWS::IAM::Policy'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 063f37b4-895f-468a-806c-cf4c038b7881
  ApiProxyRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
        Version: 2012-10-17
    Type: 'AWS::IAM::Role'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1ccb6ce5-114b-40aa-86e0-bab2d9469bb7
  CreateJobRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: bfb8ab7d-a828-4dae-9daf-c8d3fc91fcd2
  CreateJobFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code: ../modules/createJob/lambda_function.py
      Description: Puts scan parameters into the job table
      Handler: lambda_function.lambda_handler
      MemorySize: 1024
      Role: !GetAtt 
        - CreateJobRole
        - Arn
      Runtime: python3.8
      Timeout: 10
      Environment:
        Variables:
          JOBS_TABLE: !Ref JobsTable
          MAX_SEQ_LENGTH: 20000
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7e5fdb7c-849e-477b-bd32-203183c47ca5
  CreateJobPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref CreateJobFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub >-
        arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${CracklingRestApi}/*/POST/submit
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 80b5073f-fd00-42d8-a12d-e61d272405b9
  ApiGatewayLoggingRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Sub >-
          arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7264d5d4-f58a-4769-bde3-7796cdfa22e5
  ApiGatewayLoggingAccount:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !GetAtt 
        - ApiGatewayLoggingRole
        - Arn
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c32a628e-a0c5-4464-936c-e55983f5dfea
  JobsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: JobID
          AttributeType: S
      KeySchema:
        - AttributeName: JobID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3bfd580f-ae76-49e1-adc0-412ec581b212
  InsertJobPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'dynamodb:PutItem'
            Effect: Allow
            Resource: !GetAtt 
              - JobsTable
              - Arn
        Version: 2012-10-17
      PolicyName: NewJobPolicy
      Roles:
        - !Ref CreateJobRole
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1963b04f-2c09-4261-89e6-6cf7e9330fcc
  TargetScanRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 571c0a26-ee59-4ab9-9dfe-c6eb0fddbdbb
  TargetScanPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: TargetScanPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'dynamodb:PutItem'
              - 'dynamodb:BatchWriteItem'
              - 'dynamodb:Query'
            Effect: Allow
            Resource: !GetAtt 
              - TargetsTable
              - Arn
          - Action:
              - 'dynamodb:DescribeStream'
              - 'dynamodb:GetRecords'
              - 'dynamodb:GetShardIterator'
              - 'dynamodb:ListStreams'
            Effect: Allow
            Resource: !Sub >-
              arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${JobsTable}/stream/*
            Sid: Stmt5747548
      Roles:
        - !Ref TargetScanRole
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 9a137981-a570-41e7-bba0-3d05f58520a1
  TargetsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: JobID
          AttributeType: S
        - AttributeName: TargetID
          AttributeType: 'N'
      KeySchema:
        - AttributeName: JobID
          KeyType: HASH
        - AttributeName: TargetID
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 94ad6aee-7723-4408-a41d-1620a280cf3b
        
  TargetScanFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code: ../modules/targetScan/lambda_function.py
      Description: Identify potential targets in the input
      Handler: lambda_function.lambda_handler
      MemorySize: 512
      Timeout: 30
      Role: !GetAtt 
        - TargetScanRole
        - Arn
      Runtime: python3.8
      Environment:
        Variables:
          STACK_NAME: !Ref 'AWS::StackName'
          TARGETS_TABLE: !Ref TargetsTable
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ddfc2f07-2c3e-42c1-90b7-73771be6a243
        
  TargetScanEventSourceMapping:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      EventSourceArn: !GetAtt 
        - JobsTable
        - StreamArn
      FunctionName: !GetAtt 
        - TargetScanFunction
        - Arn
      StartingPosition: TRIM_HORIZON
    DependsOn: 
      - TargetScanPolicy
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1cf9d574-dd2f-401c-afe0-fd12bc830245
Metadata:
  'AWS::CloudFormation::Designer':
    1ccb6ce5-114b-40aa-86e0-bab2d9469bb7:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 630
      z: 1
      embeds: []
    063f37b4-895f-468a-806c-cf4c038b7881:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 630
      z: 1
      embeds: []
      isassociatedwith:
        - 1ccb6ce5-114b-40aa-86e0-bab2d9469bb7
    cec9eb71-520d-4c8e-b49d-6707666e37c7:
      size:
        width: 690
        height: 510
      position:
        x: 60
        'y': 90
      z: 1
      embeds:
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - 8a5ba4db-dc88-4861-87f4-c2ef066286aa
        - fa21bebf-4f0a-46de-b488-ed609ec4515c
    1237aee6-1763-4764-8e61-cff47a07a281:
      size:
        width: 240
        height: 180
      position:
        x: 60
        'y': 120
      z: 2
      parent: cec9eb71-520d-4c8e-b49d-6707666e37c7
      embeds:
        - 20c69c84-7828-4853-8398-b77a31dbe46b
      iscontainedinside:
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
    20c69c84-7828-4853-8398-b77a31dbe46b:
      size:
        width: 60
        height: 60
      position:
        x: 90
        'y': 180
      z: 3
      parent: 1237aee6-1763-4764-8e61-cff47a07a281
      embeds: []
      iscontainedinside:
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - 1237aee6-1763-4764-8e61-cff47a07a281
        - 1237aee6-1763-4764-8e61-cff47a07a281
      dependson:
        - 8a5ba4db-dc88-4861-87f4-c2ef066286aa
    8a5ba4db-dc88-4861-87f4-c2ef066286aa:
      size:
        width: 60
        height: 60
      position:
        x: 450
        'y': 180
      z: 2
      parent: cec9eb71-520d-4c8e-b49d-6707666e37c7
      embeds: []
      iscontainedinside:
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
      dependson:
        - 20c69c84-7828-4853-8398-b77a31dbe46b
    bfb8ab7d-a828-4dae-9daf-c8d3fc91fcd2:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 870
      z: 1
      embeds: []
    7e5fdb7c-849e-477b-bd32-203183c47ca5:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 750
      z: 1
      embeds: []
    80b5073f-fd00-42d8-a12d-e61d272405b9:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 750
      z: 1
      embeds: []
      isassociatedwith:
        - 7e5fdb7c-849e-477b-bd32-203183c47ca5
    fa21bebf-4f0a-46de-b488-ed609ec4515c:
      size:
        width: 60
        height: 60
      position:
        x: 330
        'y': 150
      z: 2
      parent: cec9eb71-520d-4c8e-b49d-6707666e37c7
      embeds: []
      isassociatedwith:
        - 8a5ba4db-dc88-4861-87f4-c2ef066286aa
      iscontainedinside:
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
        - cec9eb71-520d-4c8e-b49d-6707666e37c7
    7264d5d4-f58a-4769-bde3-7796cdfa22e5:
      size:
        width: 60
        height: 60
      position:
        x: 390
        'y': 660
      z: 1
      embeds: []
    c32a628e-a0c5-4464-936c-e55983f5dfea:
      size:
        width: 60
        height: 60
      position:
        x: 540
        'y': 660
      z: 1
      embeds: []
    3bfd580f-ae76-49e1-adc0-412ec581b212:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 750
      z: 1
      embeds: []
    1963b04f-2c09-4261-89e6-6cf7e9330fcc:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 870
      z: 1
      embeds: []
      isassociatedwith:
        - bfb8ab7d-a828-4dae-9daf-c8d3fc91fcd2
    94ad6aee-7723-4408-a41d-1620a280cf3b:
      size:
        width: 60
        height: 60
      position:
        x: 640
        'y': 750
      z: 1
      embeds: []
    571c0a26-ee59-4ab9-9dfe-c6eb0fddbdbb:
      size:
        width: 60
        height: 60
      position:
        x: 530
        'y': 860
      z: 1
      embeds: []
    ddfc2f07-2c3e-42c1-90b7-73771be6a243:
      size:
        width: 60
        height: 60
      position:
        x: 530
        'y': 750
      z: 1
      embeds: []
    9a137981-a570-41e7-bba0-3d05f58520a1:
      size:
        width: 60
        height: 60
      position:
        x: 640
        'y': 860
      z: 1
      embeds: []
      isassociatedwith:
        - 571c0a26-ee59-4ab9-9dfe-c6eb0fddbdbb
    1cf9d574-dd2f-401c-afe0-fd12bc830245:
      size:
        width: 60
        height: 60
      position:
        x: 390
        'y': 750
      z: 1
      embeds: []
